included:
  - Sources
  - Tests
excluded:
  - .build
  - .tuist
  - Tuist/Derived
  - .specify
opt_in_rules:
  - attributes
  - sorted_imports
  - explicit_init
disabled_rules:
  - trailing_whitespace
  - todo
  - identifier_name
line_length:
  warning: 140
  error: 200
type_body_length:
  warning: 300
  error: 500
file_length:
  warning: 600
  error: 900
reporter: "xcode"
